// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA94bu1xJQPZ2PezYMwYLqj3mcJHHsGkfk',
    appId: '1:457925400165:web:dc4164c43e3eea9086988c',
    messagingSenderId: '457925400165',
    projectId: 'green-path-31b8d',
    authDomain: 'green-path-31b8d.firebaseapp.com',
    storageBucket: 'green-path-31b8d.appspot.com',
    measurementId: 'G-M3KNR0DVQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwkiUIBvjKmghOTr4QDbVROZNjmeaWWuY',
    appId: '1:457925400165:android:eb3118467b349f1286988c',
    messagingSenderId: '457925400165',
    projectId: 'green-path-31b8d',
    storageBucket: 'green-path-31b8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgnUtNao_b8my6lIpQY4MITvT5CBI73hE',
    appId: '1:457925400165:ios:36125e80c90992a586988c',
    messagingSenderId: '457925400165',
    projectId: 'green-path-31b8d',
    storageBucket: 'green-path-31b8d.appspot.com',
    iosBundleId: 'com.example.greenPath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgnUtNao_b8my6lIpQY4MITvT5CBI73hE',
    appId: '1:457925400165:ios:36125e80c90992a586988c',
    messagingSenderId: '457925400165',
    projectId: 'green-path-31b8d',
    storageBucket: 'green-path-31b8d.appspot.com',
    iosBundleId: 'com.example.greenPath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA94bu1xJQPZ2PezYMwYLqj3mcJHHsGkfk',
    appId: '1:457925400165:web:c8afdf1cbfc0635486988c',
    messagingSenderId: '457925400165',
    projectId: 'green-path-31b8d',
    authDomain: 'green-path-31b8d.firebaseapp.com',
    storageBucket: 'green-path-31b8d.appspot.com',
    measurementId: 'G-PW53SY51J9',
  );
}
